name: Policy Onboarding

# Watch Policy branch
on:
  push:
    branches:
     # -  main

permissions:
  id-token: write
  contents: read

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Onboard to Conjur
        env:
          CONJUR_URL: "https://sme-andrew.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "agit"
        run: |
          echo "Retrieving JWT Token from Github"
          ## Handle JWT Token epoch time sync
          JWT_TOKEN=$( curl -s -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          j_body=$( echo "$JWT_TOKEN" | cut -d "." -f 2 )
          padd="=="
          jwt_padded="${j_body}${padd}"
          payload=$("$jwt_padded" | base64 -d)
          echo "$payload"
          iat=$( echo "$payload" | jq .iat )

          if (( "$iat" <= "$EPOCHSECONDS" )); then

            echo "No need to delay, authenticate away!"

          elif (( "$iat" > "$EPOCHSECONDS" )); then

            delta=$(( "$iat" - "$EPOCHSECONDS" ))
            echo "Sleeping $delta"

          else
             echo "unhandled problem"
          fi
