name: Policy Onboarding

# Watch Policy branch
on:
  push:
    branches:
     # -  main

permissions:
  id-token: write
  contents: read

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Onboard to Conjur
        env:
          CONJUR_URL: "https://sme-andrew.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "agit"
        run: |

          handle_git_jwt() {
          ## Handle JWT Token epoch time sync
    
          # Grab JWT Token from git IDP
          local JWT_TOKEN=$( curl -s -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          # Parse payload body
          j_body=$( echo "$JWT_TOKEN" | cut -d "." -f 2 )
          # Repad b64 token (dirty)
          padd="=="
          jwt_padded="${j_body}${padd}"
          #decode payload body
          payload=$(echo "$jwt_padded" | base64 -d)
          # capture IAT time
          iat=$( echo "$payload" | jq .iat )

          # Check if IAT less than or equal to server epoch
          if (( "$iat" <= "$EPOCHSECONDS" )); then

            echo "::debug No delta between iat [$iat] and epoch [$EPOCHSECONDS]"
            echo "$JWT_TOKEN"

          # check if IAT greater than server epoch, if so, calculate delta and sleep before returning
          elif (( "$iat" > "$EPOCHSECONDS" )); then

            delta=$(( "$iat" - "$EPOCHSECONDS" ))
            echo "::debug delta found: iat [$iat] // epoch [$EPOCHSECONDS]; sleeping for $delta seconds"
            sleep "$delta"
            echo "$JWT_TOKEN"

          else
            echo "::debug unhandled problem"
            exit 1 
          fi
          ####
          }
          tok=$(handle_git_jwt)
          echo $tok
