name: Policy Onboarding

# Watch Policy branch
on:
  push:
    branches:
      -  policy

permissions:
  id-token: write
  #contents: read

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Onboard to Conjur
        env:
          CONJUR_URL: ""
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "agit"
        run: |
          printenv
          git --version

