name: Policy Onboarding

# Watch Policy branch
on:
  push:
    branches:
      -  policy

permissions:
  id-token: write
  contents: read

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Onboard to Conjur
        env:
          CONJUR_URL: "https://sme-andrew.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "agit"
        run: |
          echo "Retrieving JWT Token from Github"
          t=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value)
          echo "Authenticating to Conjur"
          ct=$(curl -vv -k --request POST "$CONJUR_URL/authn-jwt/$CONJUR_SERVICE_ID/$CONJUR_ACCOUNT/authenticate" --header "Content-Type: application/x-www-form-urlencoded" --header "Accept-Encoding: base64" --data-urlencode "jwt=$t")
          echo "$ct"