name: Policy Onboarding

# Watch Policy branch
on:
  push:
    branches:
      -  policy

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Onboard to Conjur
        env:
          CONJUR_URL: ""
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "agit"
        run: |
          printenv
          git diff-tree
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
