name: Policy Onboarding

# Watch Policy branch
on:
  push:
    branches:
     # -  main

permissions:
  id-token: write
  contents: read

jobs:
  handle-policy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Onboard to Conjur
        env:
          CONJUR_URL: "https://sme-andrew.secretsmgr.cyberark.cloud/api"
          CONJUR_ACCOUNT: "conjur"
          CONJUR_SERVICE_ID: "agit"
        run: |
          set -x
          GIT_TOKEN=$(curl -vv -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          curl -v -k https://18.191.236.124/v1/auth/jwt/login -d "$GIT_TOKEN"
