name: Secret Pipeline Testing
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
jobs:
  test-credential:
    env:

      # PIPELINE RUN VARIABLES
      GOOGLE_CLIENT_ID: ""
      GOOGLE_PROJECT_ID: ""
      GOOGLE_TYPE: ""
      GOOGLE_PRIVATE_KEY_ID: ""
      GOOGLE_PRIVATE_KEY: ""
      GOOGLE_CLIENT_EMAIL: ""
      CONJUR_URL: "https://sme-andrew.secretsmgr.cyberark.cloud/api"
      CONJUR_ACCOUNT: "conjur"
      CONJUR_SERVICE_ID: "agit"
      
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
    steps:

# CyberArk Adding value:
      - name: 'Initialize Secrets'
        run: |
          GIT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | base64 -w 0)
